# Generated by Django 4.1.3 on 2022-11-27 11:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('desc', models.TextField(blank=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, error_messages={'unique': 'client with that uuid already exists.'}, unique=True)),
                ('web_url', models.URLField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='clients/')),
                ('client_type', models.CharField(blank=True, help_text='signifies if the client type is personal, college, business, school.....', max_length=50)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('desc', models.TextField(blank=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, error_messages={'unique': 'service with that uuid already exists.'}, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
