# Generated by Django 4.1.3 on 2022-11-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client_contact_partner_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_image',
            field=models.ImageField(blank=True, null=True, upload_to='clients/'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='part_image',
            field=models.ImageField(blank=True, null=True, upload_to='partners/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='ser_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
