# Generated by Django 4.1.3 on 2022-11-27 11:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('job_title', models.CharField(max_length=150)),
                ('job_req', models.TextField(blank=True, help_text='Job Requirements')),
                ('quantity', models.CharField(blank=True, help_text='Number of employees required', max_length=20)),
                ('job_role', models.TextField(blank=True, help_text='Job Responsibilities')),
                ('category', models.CharField(help_text='signifies if job category is design or development or graphics or any', max_length=50, null=True)),
                ('experience', models.CharField(blank=True, max_length=50)),
                ('job_location', models.CharField(blank=True, max_length=50)),
                ('salary', models.CharField(blank=True, max_length=25)),
                ('work_type', models.CharField(blank=True, choices=[('Remote', 'Remote'), ('Office', 'Office')], max_length=20)),
                ('submission_deadline', models.DateField()),
            ],
            options={
                'verbose_name': 'Career',
                'verbose_name_plural': 'CareerS',
            },
        ),
        migrations.CreateModel(
            name='DropCVModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('full_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=10)),
                ('email', models.EmailField(max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('cover_letter', models.TextField(blank=True)),
                ('cv', models.FileField(upload_to='cv/')),
                ('yrs_of_experience', models.CharField(max_length=50)),
                ('area_of_expertise', models.CharField(max_length=50)),
                ('job_type', models.CharField(choices=[('Internship', 'Internship'), ('Job', 'Job'), ('Freelance', 'Freelance')], max_length=50)),
            ],
            options={
                'verbose_name': 'Drop Your CV Model',
                'verbose_name_plural': 'Drop Your CV Models',
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('full_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=10)),
                ('email', models.EmailField(max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('cover_letter', models.TextField(blank=True)),
                ('cv', models.FileField(upload_to='cv/')),
                ('yrs_of_experience', models.CharField(max_length=50)),
                ('current_salary', models.CharField(max_length=10)),
                ('expected_salary', models.CharField(max_length=10)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_listed', to='careers.career')),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicants',
            },
        ),
    ]
