# Generated by Django 4.1.3 on 2022-11-18 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=150)),
                ('job_req', models.TextField(blank=True, help_text='Job Requirements')),
                ('quantity', models.CharField(blank=True, help_text='Number of employees required', max_length=20)),
                ('job_role', models.TextField(blank=True, help_text='Job Responsibilities')),
                ('category', models.CharField(help_text='signifies if job category is design or development or graphics or any', max_length=50, null=True)),
                ('experience', models.CharField(blank=True, max_length=50)),
                ('job_location', models.CharField(blank=True, max_length=50)),
                ('salary', models.CharField(blank=True, max_length=25)),
                ('work_type', models.CharField(blank=True, choices=[('Remote', 'Remote'), ('Office', 'Office')], max_length=20)),
                ('submission_deadline', models.DateField()),
            ],
            options={
                'verbose_name': 'Career Information Model',
                'verbose_name_plural': 'Career Information Models',
            },
        ),
        migrations.CreateModel(
            name='CVCareerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('cover_letter', models.TextField(blank=True)),
                ('cv', models.FileField(upload_to='')),
                ('yrs_of_experience', models.CharField(max_length=50)),
                ('area_of_expertise', models.CharField(max_length=50)),
                ('job_type', models.CharField(choices=[('Internship', 'Internship'), ('Job', 'Job'), ('Freelance', 'Freelance')], max_length=50)),
            ],
            options={
                'verbose_name': 'CV Career Apply Model',
                'verbose_name_plural': 'CV Career Apply Models',
            },
        ),
        migrations.CreateModel(
            name='CareerApplyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('cover_letter', models.TextField(blank=True)),
                ('cv', models.FileField(upload_to='')),
                ('yrs_of_experience', models.CharField(max_length=50)),
                ('current_salary', models.CharField(max_length=10)),
                ('expected_salary', models.CharField(max_length=10)),
                ('career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.careerinfomodel')),
            ],
            options={
                'verbose_name': 'Career Apply Model',
                'verbose_name_plural': 'Career Apply Models',
            },
        ),
    ]
