# Generated by Django 4.1.3 on 2022-11-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerapplymodel',
            name='cv',
            field=models.FileField(upload_to='cv/'),
        ),
        migrations.AlterField(
            model_name='cvcareermodel',
            name='cv',
            field=models.FileField(upload_to='cv/'),
        ),
    ]
