# Generated by Django 4.1.3 on 2022-12-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_alter_career_job_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={'verbose_name': 'Career', 'verbose_name_plural': 'Careers'},
        ),
        migrations.AlterField(
            model_name='dropcvmodel',
            name='area_of_expertise',
            field=models.CharField(max_length=100),
        ),
    ]
